version: "3.8"

services:
  webclipper:
    build: .
    container_name: webclipper
    ports:
      - "9069:5000"
    volumes:
      - ./data:/data
      - /volume1/Recordings:/mnt/Recordings
    restart: unless-stopped
    environment:
      - TZ=America/New_York
